import type { AddInvoiceForm } from '@/models/InvoicesModel';

export function createDefaultInvoiceForm(): AddInvoiceForm {
  return {
    choice: 0,
    category: '',
    deadline: '',
    date: '',
    currency_rate: 0,
    use_conditions: 0,
    due: '',
    object: '',
    invoice_number: '',
    client_id: '',
    referenceNumber: '',
    tax_type: 1,
    items: [],
    generalTerms: '',
    withholdingTitle:'',
    attachments: [],
    totals: {
      discount: '',
      total: '',
      taxes: '',
      subtotal: '',
    },
    watermark: '',
    language: '',
    show_description: 1,
    showArticleUnit: 1,
    showArticleTTCPrices: 0,
    show_pictures: 1,
    show_billing: 1,
    show_delivery: 0,
    show_conditions: 0,
    show_stamp: 1,
    show_bank: 0,
    selected_bank: '',
    additionalEntries: {
      tva: 0,
      fiscalStamp: 0,
      exemple: 0,
    },
    withholding_type_id: '',
    recurrence: 1,
    recurrence_start: '',
    recurrence_end: '',
    recurrence_each: 0,
    recurrence_of: 0,
    remarks: '',
  };
}
